language: generic
sudo: required
services:
  - docker

before_install:
 - docker build -t joelmuteba/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joelmuteba/docker-react npm run test